##- Download the latest version of Fedora as a base
FROM registry.fedoraproject.org/fedora

##- Label the container
LABEL maintainer="Scruffington"

##- Update the container
RUN dnf update -y

##- Download steamcmd
